import type { Config } from "tailwindcss";

const config: Config = {
  content: [
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
    "./pages/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    fontSize: {
      '2xs':  '0.9vw',
      '3xs':  '0.8vw',
      '4xs':  '0.7vw',
      '5xs':  '0.6vw',
      'xs':   '1vw',
      'sm':   '1.1vw',
      'md':   '1.2vw',
      'xl':   '1.4vw',
      '4xl':  '1.7vw',
      '5xl':  '1.8vw',
      '8xl':  '2.1vw',
      '9xl':  '2.2vw',
      '10xl': '2.3vw',
      '11xl': '2.4vw',
      '15xl': '2.8vw',
      '16xl': '2.9vw',
      '18xl': '3.1vw',
      '19xl': '3.2vw',
      '20xl': '3.3vw',
      '50xl': '6.3vw',
    },
    extend: {
      padding: {
        '2xs':  '1vw',
        '3xs':  '0.8vw',
        '4xs':  '0.6vw',
        '5xs':  '0.4vw',
        '6xs':  '0.2vw',
        '7xs':  '0.1vw',
        'xs':   '1.2vw',
        'sm':   '1.4vw',
        'md':   '1.6vw',
        'xl':   '2vw',
        '3xl':  '2.4vw',
        '4xl':  '2.6vw',
        '5xl':  '2.8vw',
        '8xl':  '3.4vw',
        '10xl': '3.8vw',
        '12xl': '4.2vw',
        '26xl': '7vw',
        '64xl': '14.6vw',
      },
      gap: {
        '7xs':  '0.1vw',
        '5xs':  '0.5vw',
        '4xs':  '0.7vw',
        '2xs':  '1.1vw',
        'xs':   '1.3vw',
        'sm':   '1.5vw',
        'md':   '1.8vw',
        'lg':   '2vw',
        '2xl':  '2.5vw',
        '3xl':  '3vw',
        '4xl':  '3.5vw',
        '5xl':  '4vw',
        '6xl':  '4.5vw',
        '7xl':  '5vw',
        '8xl':  '5.5vw',
        '10xl': '6.5vw',
        '12xl': '7.5vw',
        '13xl': '8vw',
        '16xl': '9.5vw',
        '20xl': '11.5vw',
      },
      margin: {
        '2xs':  '1vw',
        '3xs':  '0.8vw',
        '4xs':  '0.6vw',
        'md':   '1.6vw',
        '3xl':  '2.4vw',
      },
      colors: {
        "white-1": "#F8F8F8",
        "white-2": "#e8e8e8",
        "grey-1":  "#dddddd",
        "grey-2":  "#d4d4d4",
        "blue-1":  "#005EBE",
        "blue-2":  "#E9F5FE",
        "blue-3":  "#F5F7F9",
        "red-1":   "#FF0000",
        'sky':     '#3eb9e2',
      },
      boxShadow: {
        'box-1': '3px 3px 8px #00000080',
        'box-2': '2px 2px 7px #00000080',
      },
      backgroundImage: {
        'blue-mob':  'url("/bg/svg/blue-mob.svg")',
        'blue-desk': 'url("/bg/svg/blue-desk.svg")',
      },
    },
  },
  plugins: [],
};

export default config;
